### ISSUE TITLE
Wrong colors gruvbox dark theme [st 0.8.1]

### ISSUE THREAD

**Issue by davidarrieta** [honza/base16-st#3]
Hi, first of all, congratulations for your excellent work. 
I have this problem with [st and gruvbox-dark-medium](https://imgur.com/a/IQrhl7v) that the colors are never correct as they are in [urxvt with the same theme](https://imgur.com/a/09wtNKy), but one thing I noticed is that when I use [st with base16 shell](https://imgur.com/a/zt5lUZK) the colors are identical to those of urxvt.

[My Xresources](https://github.com/davidarrieta/dotfiles/blob/master/Xresources/.Xresources)

[My actual config.h](https://pastebin.ubuntu.com/p/ZpzJt5hSHx/)

**Comment by honza** [comment]
I just pushed an update. Would you mind trying it?

**Comment by davidarrieta** [comment]
The same problem remains but [now it seems that the main colours are grey and reddish orange.](https://imgur.com/a/l4pRQTM)

**Comment by davidarrieta** [comment]
So... you didn't get a solution?

**Comment by brianbuccola** [comment]
The problem seems to be that base00 - base07 are all various shades of gray (dark to light), while only base08 - base0F are regular colors (red, orange, yellow, green, blue, cyan, magenta, dark orange). st expects 8 normal colors + 8 bright colors, but currently this means that the bright colors are all just various shades of gray (plus dark orange).

One easy fix is to just make the (non-black/white) normal colors and (non-black/white) bright colors exactly the same:

```c
	/* base16-gruvbox-dark-hard */
	"#1d2021", /* base00 black          */
	"#fb4934", /* base08 red            */
	"#b8bb26", /* base0B green          */
	"#fabd2f", /* base0A yellow         */
	"#83a598", /* base0D blue           */
	"#d3869b", /* base0E magenta        */
	"#8ec07c", /* base0C cyan           */
	"#d5c4a1", /* base05 white          */

	"#665c54", /* base03 bright black   */
	"#fb4934", /* base09 bright red     */
	"#b8bb26", /* base01 bright green   */
	"#fabd2f", /* base02 bright yellow  */
	"#83a598", /* base04 bright blue    */
	"#d3869b", /* base06 bright magenta */
	"#8ec07c", /* base0F bright cyan    */
	"#fbf1c7", /* base07 bright white   */
```

For what it's worth, here is the non-base16 version of gruvbox dark, taken from [gruvbox-contrib/st/gruvbox-dark.h](https://github.com/morhetz/gruvbox-contrib/blob/master/st/gruvbox-dark.h):

```c
	/* gruvbox-dark-hard */
	"#1d2021",  /*  0: black          */
	"#cc241d",  /*  1: red            */
	"#98971a",  /*  2: green          */
	"#d79921",  /*  3: yellow         */
	"#458588",  /*  4: blue           */
	"#b16286",  /*  5: magenta        */
	"#689d6a",  /*  6: cyan           */
	"#a89984",  /*  7: white          */

	"#928374",  /*  8: bright black   */
	"#fb4934",  /*  9: bright red     */
	"#b8bb26",  /* 10: bright green   */
	"#fabd2f",  /* 11: bright yellow  */
	"#83a598",  /* 12: bright blue    */
	"#d3869b",  /* 13: bright magenta */
	"#8ec07c",  /* 14: bright cyan    */
	"#ebdbb2",  /* 15: bright white   */
```

As you can see, base16 uses gruvbox's bright colors as its normal colors.
